### ISSUE TITLE
支持ES版本为5.X的吗？

### ISSUE THREAD

**Issue by amsenhao** [infinilabs/console#10]
看特性说明是支持5.X版本的，但是使用时要求ES版本为7.3以上版本，怎么设置支持低版本的ES？
![Uploading bd654220b4f928437da8126189110d1.png…]()

**Comment by silenceqi** [comment]
Console 本身是需要一个 ES 集群来存储系统数据的，这个 ES 集群 Console [最新版本](http://release.infinilabs.com/console/snapshot/console-0.8.2_SNAPSHOT-969-linux-amd64.tar.gz)的要求是 5.3 或以上, 但是系统纳管的 ES 集群 版本是支持 5.x 的
