### ISSUE TITLE
nginx proxy 

### ISSUE THREAD

**Issue by fv0008** [infinilabs/console#11]
console can use yaml to config nginx proxy like http://xxxx:9000/ and use https to proxy http?

**Comment by medcl** [comment]
are you mean to use nginx to proxy console?

**Comment by fv0008** [comment]
yes
like https://www.xxx.com/console to proxy http://localhost:9000/

**Comment by medcl** [comment]
it should works, i see no reason why it can't.

**Comment by fv0008** [comment]
给个配置例子呗
或则可以让nginx可以location /console 对齐 localhost:9000/console 呗，手册里没看到

**Comment by medcl** [comment]
标准的 Nginx HTTP 转发，完整的文档可以去 Nginx 的这个页面查看哈：https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
