### ISSUE TITLE
监控报表不显示集群监控等数据

### ISSUE THREAD

**Issue by CCczya** [infinilabs/console#12]
**问题**
![image](https://user-images.githubusercontent.com/84966725/230849690-edab00ae-a78d-46da-8283-4b1b72b050e4.png)
![image](https://user-images.githubusercontent.com/84966725/230849755-2fd89ff3-a337-46f3-8b4c-526b69445b46.png)
**版本**
![image](https://user-images.githubusercontent.com/84966725/230850067-b2cb7b65-08c5-495f-ac16-a66f14a8e939.png)
已经更新到最新版本，还是不行，数据存储的ES版本是7.7.0

**Comment by silenceqi** [comment]
console 服务端有报错误日志吗

**Comment by CCczya** [comment]
> console 服务端有报错日志吗

没有

**Comment by CCczya** [comment]
> console 服务端有报错日志吗

![image](https://user-images.githubusercontent.com/84966725/230858273-1ce91421-f368-4a7f-855e-cb203d6ebbd3.png)
刷的都是这些日志

**Comment by silenceqi** [comment]
把 console 地址在网关管理里面注册，
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/4121340/230860696-e8bfb079-6bf6-4670-b38d-45c99cde4ee4.png">
然后看下 队列消费的情况
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/4121340/230861218-7e6bd15d-6938-40af-971f-a59d37d88738.png">
点击刷新之后，offset 是否有变化

**Comment by CCczya** [comment]
> 把 console 地址在网关管理里面注册， <img alt="image" width="1423" src="https://user-images.githubusercontent.com/4121340/230860696-e8bfb079-6bf6-4670-b38d-45c99cde4ee4.png"> 然后看下 队列消费的情况 <img alt="image" width="1421" src="https://user-images.githubusercontent.com/4121340/230861218-7e6bd15d-6938-40af-971f-a59d37d88738.png"> 点击刷新之后，offset 是否有变化

![image](https://user-images.githubusercontent.com/84966725/230870628-0305794b-be64-4c8f-8d79-603f0e69ce3b.png)
![image](https://user-images.githubusercontent.com/84966725/230870662-82f2c74a-fd48-4b9d-91a2-52206b7aa8f6.png)
没有队列数据

**Comment by silenceqi** [comment]
![img_v2_6743d690-b0d0-4ffd-85db-2e28024ef47g](https://user-images.githubusercontent.com/4121340/230887919-94cd2c19-75d7-46a4-809b-35ffacb68274.png)
wx 加下小助手，联系我们
