### ISSUE TITLE
setup not permitted

### ISSUE THREAD

**Issue by lianmeng0** [infinilabs/console#13]
安装后，添加ES集群配置，集群连接测试可以正常，初始化时提示删除以.infini_开头的索引或者跳过，当点击跳过后进入第三步设置
输入账号信息后点击下一步会报错：
start to initialize template [template_ilm]
PUT /_template/.infini {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Custom Analyzer [suggest_text_search] failed to find tokenizer under name [classic]"}],"type":"illegal_argument_exception","reason":"Custom Analyzer [suggest_text_search] failed to find tokenizer under name [classic]"},"status":400}

查看网关常见问题，执行命令：
DELETE _template/.infini
DELETE .infini_node
DELETE .infini_index

重新启动还会报错：
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyzer [suggest_text_search] has not been configured in mappings"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: analyzer [suggest_text_search] has not been configured in mappings","caused_by":{"type":"illegal_argument_exception","reason":"analyzer [suggest_text_search] has not been configured in mappings"}},"status":400}
当再次刷新后就会报错：
setup not permitted

使用版本：
/console-linux-amd64 -v
console 1.23.0 1438 2024-02-29 04:25:40 +0000 UTC 2024-12-31 10:10:10 +0000 UTC 200ffd7af684ba2b7cd221e9bdece9f18653017f

启动命令：
./console-linux-amd64

**Comment by medcl** [comment]
如果之前没有初始过，不能跳过哦，因为 Console 需要初始化一下默认的模版和索引，当系统集群里面的数据都是正常的，如升级的时候，则可以选择跳过，否则是需要初始化才行的，另外系统集群建议和业务集群分开。

**Comment by lianmeng0** [comment]
> 如果之前没有初始过，不能跳过哦，因为 Console 需要初始化一下默认的模版和索引，当系统集群里面的数据都是正常的，如升级的时候，则可以选择跳过，否则是需要初始化才行的，另外系统集群建议和业务集群分开。

你好！本次测试安装没有进行任何步骤的跳过，错误也进行解决了，但是同样的在进行第三步设置时，还是报错：无法设置
![image](https://github.com/infinilabs/console/assets/108977391/cb2972d2-7ca6-473f-97dd-0c14e216309c)

在进行初始话时，有个报错：
PUT /_template/.infini {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Custom Analyzer [suggest_text_search] failed to find tokenizer under name [classic]"}],"type":"illegal_argument_exception","reason":"Custom Analyzer [suggest_text_search] failed to find tokenizer under name [classic]"},"status":400}

进行修改：
"tokenizer": "ik_max_word"
删除使用过滤器
手动创建模板，然后进行初始化中其余4个小模块

**Comment by medcl** [comment]
@lianmeng0 这是用的什么版本的 ES 啊？

**Comment by lianmeng0** [comment]
> @lianmeng0 这是用的什么版本的 ES 啊？

使用的是7.15.1版本，但是分词器是公司自己改造的

**Comment by medcl** [comment]
新版本流程已优化，欢迎测试
