### ISSUE TITLE
2 个集群 每天生成好多日志，见截图，这些都是什么日志？是否可以配置

### ISSUE THREAD

**Issue by a-nuo** [infinilabs/console#5]
![consolelog](https://user-images.githubusercontent.com/12962793/149073323-9f8cd8a1-b466-4fbc-b432-f4afdb4e11de.jpg)

**Comment by medcl** [comment]
这个是集群元数据的变更记录，修改 elastic 配置的这个参数就行了。
```
elastic:
    metadata_refresh:
      enabled: false
```

**Comment by medcl** [comment]
现在放队列里面的，后续会用到这个数据，暂时没有消费。

**Comment by a-nuo** [comment]
OK
