### ISSUE TITLE
请问0.2.0升级0.3.0，“常用命令”数据如何迁移？

### ISSUE THREAD

**Issue by a-nuo** [infinilabs/console#6]

**Comment by medcl** [comment]
换集群了么，还是就是本集群

**Comment by a-nuo** [comment]
本集群，已经解决了

**Comment by a-nuo** [comment]
POST _reindex
{
  "source": {"index": ".infini_commoncommand"},
  "dest":{
    "index":".infini_commands"
  }
}

**Comment by medcl** [comment]
👍
