### ISSUE TITLE
版本console-0.6.0-841 运行一段时间后报错

### ISSUE THREAD

**Issue by zzpshenaini** [infinilabs/console#8]
error in bulk_indexing worker[ce6t2lsjordii17asmg0],queue:[ce6l4h4jordi7k6k8u40], slice:[0], offset:[2,64603355]->[2,64603355],FlushFileBuffers: The handle is invalid.
![73FA1BE3-8FCC-41ad-AF0A-2C07183768C0](https://user-images.githubusercontent.com/15992547/205625682-7413010f-8673-4431-8816-dfda5f15a97b.png)

**Comment by medcl** [comment]
windows 么？
